---
apiVersion: v1
kind: Service
metadata:
  name: fathom-lb-svc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: http
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "wingedblade-session"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "300"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "92e73c98-1cb9-4780-bf2c-1457f27b2d9c"
spec:
  type: LoadBalancer
  selector:
    app: fathom
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fathom-deployment
  labels:
    app: fathom
spec:
  replicas: 20
  selector:
    matchLabels:
      app: fathom
  template:
    metadata:
      labels:
        app: fathom
    spec:
      containers:
      - name: fathom
        image: quay.io/chrisshort/fathom:latest
        ports:
        - containerPort: 8080
        env:
        - name: FDBSTRG
          valueFrom:
            secretKeyRef:
              name: psql-env-vars
              key: FDBSTRG
        - name: FSECRET
          valueFrom:
            secretKeyRef:
              name: psql-env-vars
              key: FSECRET
        resources:
          requests:
            memory: "24Mi"
            cpu: "100m"
          limits:
            memory: "96Mi"
            cpu: "300m"