---
apiVersion: v1
kind: Service
metadata:
  name: fathom-lb-svc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "wingedblade"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "60"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "cert-wingedblade"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: fathom
  ports:
    - name: http
      protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      nodePort: 30001
      port: 443
      targetPort: 8080
